// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: api/proto/calculator.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BinaryOperation represents an operation on two numbers
type BinaryOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryOperation) Reset() {
	*x = BinaryOperation{}
	mi := &file_api_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryOperation) ProtoMessage() {}

func (x *BinaryOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryOperation.ProtoReflect.Descriptor instead.
func (*BinaryOperation) Descriptor() ([]byte, []int) {
	return file_api_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryOperation) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *BinaryOperation) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

// Result represents the result of an operation
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_api_proto_calculator_proto protoreflect.FileDescriptor

const file_api_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/calculator.proto\x12\n" +
	"calculator\"-\n" +
	"\x0fBinaryOperation\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"\x1e\n" +
	"\x06Result\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value2\x80\x02\n" +
	"\x11CalculatorService\x126\n" +
	"\x03Add\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.Result\x12;\n" +
	"\bMultiply\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.Result\x12;\n" +
	"\bSubtract\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.Result\x129\n" +
	"\x06Divide\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.ResultBIZGgithub.com/cont1nu1ty/distributed-systems-go-demos/api/proto/calculatorb\x06proto3"

var (
	file_api_proto_calculator_proto_rawDescOnce sync.Once
	file_api_proto_calculator_proto_rawDescData []byte
)

func file_api_proto_calculator_proto_rawDescGZIP() []byte {
	file_api_proto_calculator_proto_rawDescOnce.Do(func() {
		file_api_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_calculator_proto_rawDesc), len(file_api_proto_calculator_proto_rawDesc)))
	})
	return file_api_proto_calculator_proto_rawDescData
}

var file_api_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_calculator_proto_goTypes = []any{
	(*BinaryOperation)(nil), // 0: calculator.BinaryOperation
	(*Result)(nil),          // 1: calculator.Result
}
var file_api_proto_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculatorService.Add:input_type -> calculator.BinaryOperation
	0, // 1: calculator.CalculatorService.Multiply:input_type -> calculator.BinaryOperation
	0, // 2: calculator.CalculatorService.Subtract:input_type -> calculator.BinaryOperation
	0, // 3: calculator.CalculatorService.Divide:input_type -> calculator.BinaryOperation
	1, // 4: calculator.CalculatorService.Add:output_type -> calculator.Result
	1, // 5: calculator.CalculatorService.Multiply:output_type -> calculator.Result
	1, // 6: calculator.CalculatorService.Subtract:output_type -> calculator.Result
	1, // 7: calculator.CalculatorService.Divide:output_type -> calculator.Result
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_calculator_proto_init() }
func file_api_proto_calculator_proto_init() {
	if File_api_proto_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_calculator_proto_rawDesc), len(file_api_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_calculator_proto_goTypes,
		DependencyIndexes: file_api_proto_calculator_proto_depIdxs,
		MessageInfos:      file_api_proto_calculator_proto_msgTypes,
	}.Build()
	File_api_proto_calculator_proto = out.File
	file_api_proto_calculator_proto_goTypes = nil
	file_api_proto_calculator_proto_depIdxs = nil
}
